### ISSUE TITLE
Repository cancel_process endpoint fails if no processings exist

### ISSUE THREAD

**Issue by marcheing** [mezuro/kalibro_processor#120]
The cancel_process method of the Repository controller takes the last of all the processings, and immediately uses it, assuming it exists. If it is not the case, an exception will happen, and internal server error is returned.

We should properly handle this case and do nothing, or return a correct error code.

**Comment by rafamanzo** [comment]
Nice catch! For sure it's a bug.

Adding some context, it was not handled before because there isn't a case on Prezento where a Repository has no Processings. Since a call to RepositoriesController#create (https://github.com/mezuro/prezento/blob/master/app/controllers/repositories_controller.rb#L143) triggers a call to RepositoriesController#process_repository.
