### ISSUE TITLE
TreeMetricResult specific requests routes

### ISSUE THREAD

**Issue by rafamanzo** [mezuro/kalibro_processor#141]
Refactor the routes so requests specifics to TreeMetricResults respond under `/tree_metric_results/...` instead of `/metric_results/...`.

**Comment by marcheing** [comment]
What do you think about having all the routes have the concrete class (TreeMetricResult => tree_metric_results, HotspotMetricResult => hotspot_metric_results) and have their controllers to inherit from a common controller class with MetricResult methods?

It's a good chance we have to improve the API since we have to break it anyway.

**Comment by rafamanzo** [comment]
Yes, thats nice :)

Just like we do with `MetricConfiguration` and `CompoundMetricConfiguration` on Prezento, right?

**Comment by marcheing** [comment]
Done, check out commit 84ad24f

**Comment by rafamanzo** [comment]
Closing as this is already in the mainstream.
