### ISSUE TITLE
Pymetrics

### ISSUE THREAD

**Issue by diegoamc** [mezuro/kalibro_processor#83]
Add python metric collector Pymetrics:
http://pymetrics.sourceforge.net/

We already have a collector, Analizo. (https://github.com/mezuro/kalibro_processor/blob/master/lib/metric_collector/native/analizo.rb)

Now we are implementing Ruby collectors. (https://github.com/mezuro/kalibro_processor/tree/flog/lib/metric_collector/native/metric_fu)

**Comment by ParleyMartins** [comment]
UnB Team will do this.

**Comment by rafamanzo** [comment]
Have a look at this message with discussions regarding this issue: http://librelist.com/browser//mezuro/2015/3/24/unb-team-progress/#554ae2e88b60502de9115e54a7148e20

**Comment by rafamanzo** [comment]
Have a look at this PR for a summary of all the modifications made in order to add a Ruby metrics collector: https://github.com/mezuro/kalibro_processor/pull/84

**Comment by rafamanzo** [comment]
With a litle bit more details, try to follow the MetricFu stantard on implementing this new collector instead of Analizo's (MetricFu is newer and has a better design).

Second, try to add a collector with useful quality metrics like cyclomatic complexity. We have interest on code style metrics, like limited character per line, but we are more insterested on the first ones. So pylint is probably not our priority.

**Comment by seocam** [comment]
Would be nice to use radon: https://github.com/rubik/radon

**Comment by marcheing** [comment]
Closed by #126
